export const highlightsOrder = [
	{ id: 1, title: 'Alerta 🚨' },
	{ id: 2, title: 'Goold Paga 💵' },
	{ id: 3, title: 'Quiosques 🩷✨' },
	{ id: 4, title: 'Eventos 🚀✨' },
	{ id: 5, title: 'Tônico Poderoso' },
	{ id: 6, title: 'Rec. Poderosa 💚' },
	{ id: 7, title: 'Linha Poderosa🧡' },
	{ id: 8, title: 'Shampeeling 🩷' },
	{ id: 9, title: 'Rep. Poderoso 🧡' },
	{ id: 10, title: 'Repare Gold 💙' },
	{ id: 11, title: 'Linha Babosa 💚' },
	{ id: 12, title: 'Linha Dnaplex ❤️' },
	{ id: 13, title: 'Linha Soneca 💗' },
	{ id: 14, title: 'Cronograma ✨' },
	{ id: 15, title: 'Cronoterapia' },
	{ id: 16, title: 'R. Obrigatória' },
	{ id: 17, title: 'Terapiatox 🩷' },
	{ id: 18, title: 'Mil. Pós Quimic' },
	{ id: 19, title: 'Skin Care 🩷' },
	{ id: 20, title: 'AcidGold' },
	{ id: 21, title: 'R. Milagrosa 💜' },
];
